### ISSUE TITLE
Scaling shared between queries in visualize_multiplot

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/ChEBI2Plot#1]
I made a mock Agilent results file with only three entries, and noticed that the plot adjusts to cover only these three data points. However, this scaling is carried forward to the subsequent plots, e.g. for Bruker:

![multiplot](https://user-images.githubusercontent.com/16084125/73654805-e0da7380-468c-11ea-95b7-f799cb70abd9.png)

**Comment by magnuspalmblad** [comment]
I think the R version has defaults [-5.5, 10.5] and [0, 1600] in log P and mass respectively.

**Comment by ReinV** [comment]
New script now has default [-5, 10] and [0, 1600] but these can also be manually adjusted with arguments -xmin -xmax and -ymax. 

Additionally scaling is now no longer shared between queries.
