### ISSUE TITLE
Error after reading searches_by_year

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/ChEBI2Plot#5]
I copied 4 of the searches by year csv files in the Google Drive folder to searches_by_year and tried to run make_table.py. Unfortunately, I get this kind of error after the "reading files with properties" step:

$ python ./make_table.py -i results -t folder
Input file contains 14485 unique ChEBI IDs
Input file contains 7128 unique ChEBI IDs
Input file contains 6769 unique ChEBI IDs
Input file contains 617 unique ChEBI IDs
Input file contains 5375 unique ChEBI IDs
Input file contains 241 unique ChEBI IDs
Input file contains 8312 unique ChEBI IDs
reading files for normalization...
searches_by_year/from_knime_2015.csv
searches_by_year/from_knime_2016.csv
searches_by_year/from_knime_2017.csv
searches_by_year/from_knime_2018.csv
perform normalization...
reading files with properties...
Traceback (most recent call last):
  File "./make_table.py", line 207, in <module>
    main()
  File "./make_table.py", line 196, in main
    data = read_file(file, key, data)
  File "./make_table.py", line 119, in read_file
    info = line_to_list[1].strip()
IndexError: list index out of range

**Comment by ReinV** [comment]
make_table.py needs some files from the "files" folder (e.g. ChEBI2mass, ChEBI2logP). Am I correct in thinking those might be missing now?

**Comment by magnuspalmblad** [comment]
I have the following files in the "files" folder:

**Comment by magnuspalmblad** [comment]
I have the following files in the "files" folder:

$ ls files/
ChEBI2logP.tsv  ChEBI2Names.tsv       ChEBI2Superterms_roles.tsv
ChEBI2logS.tsv  ChEBI2Smiles.tsv      new_smiles.txt
ChEBI2Mass.tsv  ChEBI2Superterms.tsv  ontology_version.txt

**Comment by magnuspalmblad** [comment]
The error seems to come from the 

info = line_to_list[1].strip()

line. Perhaps there is a line which does not contain any tab, so that line_to_list[1] is null?

**Comment by magnuspalmblad** [comment]
Did you convert the searches_by_year CSV files to TSV?

**Comment by ReinV** [comment]
> Perhaps there is a line which does not contain any tab, so that line_to_list[1] is null?

That is possible, but then I should have seen the same error. Maybe that line only occurs in the latest updated ChEBI files. I will test that now.


> Did you convert the searches_by_year CSV files to TSV?

No.

**Comment by magnuspalmblad** [comment]
Just to rule it out, I checked all lines in the results contain at least one tab:

$ for x in *.tsv; do echo -n $x; awk '/\t/{N++}END{print " " N}' $x; done
GC_ChEBI_IDs.tsv **2996076**
HILIC_ChEBI_IDs.tsv **367412**

$ wc *.tsv
 **2996076**  5992152 47746368 GC_ChEBI_IDs.tsv
  **367412**   734824  5858911 HILIC_ChEBI_IDs.tsv
 3363488  6726976 53605279 total

**Comment by ReinV** [comment]
I cannot recreate the error. Can you replace the read_file code with the following code:

```
    f = open(file, 'r')
    lines = f.readlines()
    id_to_info = dict()
    for line in lines:
        line_to_list = line.split('\t')
        try: 
            id = line_to_list[0]
            info = line_to_list[1].strip()
            id_to_info[id] = info
        except:
            print(line)
            print(file)
    data[key] = id_to_info

    return data
```

and report back what is printed? Should help us understand what is going on.

**Comment by magnuspalmblad** [comment]
I did something similar [adding a print(id,info)], and is seems it crashes after reading ChEBI2logP.tsv:

Will try your fix now.

...
22798 -
145215 -0.14
145026 -2.17
145408 -
Traceback (most recent call last):
  File "./make_table.py", line 208, in <module>
    main()
  File "./make_table.py", line 197, in main
    data = read_file(file, key, data)
  File "./make_table.py", line 119, in read_file
    info = line_to_list[1].strip()
IndexError: list index out of range

**Comment by magnuspalmblad** [comment]
$ python ./make_table.py -i results -t folder
Input file contains 14485 unique ChEBI IDs
Input file contains 7128 unique ChEBI IDs
reading files for normalization...
searches_by_year/from_knime_2015.csv
searches_by_year/from_knime_2016.csv
searches_by_year/from_knime_2017.csv
searches_by_year/from_knime_2018.csv
perform normalization...
reading files with properties...
version https://git-lfs.github.com/spec/v1

files/ChEBI2Superterms.tsv
oid sha256:704f8c4547ff00b4e92b068473638c4b75c6e3a1825f7b658c7d6fe7c7c33d7a

files/ChEBI2Superterms.tsv
size 52828611

files/ChEBI2Superterms.tsv
making the table...
From 14485 of 14485 ChEBI IDs not all properties could be found
From 7128 of 7128 ChEBI IDs not all properties could be found

**Comment by ReinV** [comment]
> version https://git-lfs.github.com/spec/v1
> oid sha256:704f8c4547ff00b4e92b068473638c4b75c6e3a1825f7b658c7d6fe7c7c33d7a
> size 52828611

Lines like this should not be in the ChEBI2 files and I don't understand how they ended up there! Can you see those lines when you open the file (maybe at the start or the end) ?

**Comment by magnuspalmblad** [comment]
I assume finding a ChEBI ID not covered in the files should not cause an exception. The expected behavior would be either that it is ignored, or that you get a warning.

Will remove those lines now!

**Comment by magnuspalmblad** [comment]
Aha - maybe those files were too large for GitHub? Those lines are all that it is in the ChEBI2Superterms files.

**Comment by magnuspalmblad** [comment]
The are labeled "Stored with Git LFS", and apparently they have to be downloaded individually from GitHub...

**Comment by ReinV** [comment]
Ah yes, they indeed were too large for GitHub so I had to upload them with Git LFS which is also the link that got printed.

**Comment by magnuspalmblad** [comment]
Learning something new everyday! Now I got the tables, so I will close this issue and move on to generating the plots!
